# Generated by Django 2.2.6 on 2019-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_auto_20191030_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img'),
        ),
    ]
