# Generated by Django 2.2.6 on 2019-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_auto_20191103_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_Alquiler', models.DateField(auto_now=True, verbose_name='Fecha Alquiler')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha Devolución')),
                ('cliente_id', models.ManyToManyField(to='libro.Cliente')),
                ('libro_id', models.ManyToManyField(to='libro.Libro')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['fecha_Alquiler'],
            },
        ),
    ]
